### ISSUE TITLE
Possibilities for adding bespoke settings

### ISSUE THREAD

**Issue by AntonOfTheWoods** [NYPL/web-reader#107]
I need to add a set of settings (gloss types) that would ideally go as a new row in the main HTML settings popout. There doesn't appear to be any way to do this currently. One hacky work-around would be to include an extra block/button with the `headerLeft` - at least it is in the header and isn't totally illogical. Thinking of that solution got me thinking it would be nice to be able to reproduce the `ToggleGroup` and `ToggleButton`, but as these aren't exported from the package currently, that would mean copy/pasting them...

Is this something you would consider PRs for? What sort of solution would you be willing to consider? Would a prop that can contain an element that gets injected at the bottom (if supplied) be ok?

(ping @kristojorg )

**Comment by kristojorg** [comment]
Hey Anton, thanks for opening the issue! Creating custom UI around your reader is definitely something we want to support, and was considered in the architecture we came up with for this. What we _dont_ want to have happen though is to create a `<WebReader>` export with many many different options that eventually conflict and become difficult to test/manage. So essentially, the current `<WebReader>` export is meant to include a _default_ UI that isn't really customizable. We only provide the single `headerLeft` prop because without that piece of customization the `<WebReader>` would not have a back button, and the default UI would be basically useless.

Instead, the way I envision this is that we provide you the tools you need to build _any_ custom UI you would like while utilizing the same logic and API that we have. You would use the `useWebReader` hook from this library, and then make your own wrapper:

```tsx
import { useWebReader, ReaderNav, ReaderFooter } from 'nypl/web-reader';

const CustomizedReaderPage = ({ webpubManifestUrl }) => {
  const reader = useWebReader({
    webpubManifestUrl,
  });

  return (
    <div>
      {/* eg. keep default header, but change its background */}
      <ReaderNav {...reader} className="bg-blue" />

      {/* we can add custom prev/next page buttons */}
      <button onClick={reader.handleNextPage}>Next</button>
      <button onClick={reader.handlePrevPage}>Prev</button>

      {/* you will receive content from the reader to render wherever you want */}
      {reader.content}

      {/* use the default footer */}
      <ReaderFooter {...reader} />
    </div>
  );
};
```

This is something that we admittedly don't fully support yet, mainly because we don't export all the existing UI elements (which you can use or ignore and build your own) and because we lack the documentation. 

I can create a ticket to address this internally, but we are currently working on some refactor and stability work, so it might not happen for a bit. What I would suggest to get this done as soon as possible is to make a PR exporting all of the UI components. These would be the steps:

1. Make a file at `src/ui/index.ts` and from there export all our components such as `<Header>`, `<HtmlSettings>`, `<PdfSettings>`, `<Button>`, `<ToggleButton>`, `<ToggleGroup>`, etc. via `export { default as Header } from "./Header"`.
1. Export all of `src/ui/index.ts` from `src/index.tsx` with `export * as UI from "./ui"`
1. Make this into a PR
1. Some of the components might need to be extracted from other components, for example you might want to extract the footer that is currently defined as part of `<WebReaderContent>` in `src/ui/manager.tsx` into a `<Footer>` and export that so you can use it easier. Reorganization like that can go into a follow up PR, or the same PR as the first. Up to you.

Once that is done, you'll want to create your custom UI in the same way that `manager.tsx` creates our default UI, but you can replace any of the code or components in there with your own if you like.

You can also add an example to the example app (`npm run example`) using a custom UI that imports some of those components, and you could write some cypress tests for it also if you like. That will make ensure we don't break any of the imports or features you're using in the future. 

I hope this is helpful, and if you get a PR started, I'm happy to help and contribute as I can!

**Comment by AntonOfTheWoods** [comment]
Thanks very much for your quick reply @kristojorg ! That sounds totally logical and doable, and your explanation seems clear and complete. I'll definitely get onto it, though it may have to wait for a bit as the next month or so is going to be super busy.

**Comment by AntonOfTheWoods** [comment]
Unfortunately, after spending several entire days trying to make headway I gave up, copy/pasted a few things (basically some of the caching logic and the types), removed what I'm not using (Axis and PDF) and rewrote the UI in MUI. I initially hoped that it would be possible for us to collaborate but I'm simply not expert enough in modern JS, and small bugs were taking longer to debug than it ended up taking to reimplement what I actually need in MUI.

I'll definitely keep an eye on how things go here though!
