### ISSUE TITLE
Make a buildable example using npm reference and no axisnow

### ISSUE THREAD

**Issue by AntonOfTheWoods** [NYPL/web-reader#114]
In trying to use the Readme's example code and suggestions, it is extremely difficult to work out what is a potential feature contribution and what is a potential bugfix contribution.

As it stands, there is private NYPL code that is required to even build the example, making it impossible to easily determine what is a bug and what is a potential fantastic new feature :-D.

Would you be open to having a working example that uses no relative imports (so no `import initWebReaderSW from '../src/ServiceWorker/sw';`, which obscures the fact that this method is not exported from the package, and so not easily usable in certain webpack contexts), and no private code? This would make contributing much easier and mean that it is much, much clearer how non-NYPL teams can use the package as available on NPM!

**Comment by hokei** [comment]
Hi!  Thank you - due to the backlog of stuff we have, we don't do specific testing for use cases outside NYPL, which means we don't normally test the app without the private package.  The fact that it can't run without the internal packages is a bug, and we would definitely welcome a fix for the bug.  If this is a thing that can't be fixed without access to the package, we'll put it on our roadmap to fix, but I don't know when that fix will be available.

We would rather not maintain two different example applications, though, so if possible we'd like to preserve the current design, where all examples work except the one that uses Axis decryption.

**Comment by samanthaandrews** [comment]
Hi @AntonOfTheWoods I might be able to help in getting examples to run without access to the internal packages. Do you receive an error when running `npm install` on the project? If possible, can you post the error message or stack trace you're seeing?

With regard to the example you requested, I know this isn't exactly what you're looking for, but in the `example/index.tsx` file, you'll see how we are using the <WebReader /> component in several different contexts, passing different props depending on what content we're rendering. The only difference would be that instead of `import WebReader from '../src'`, you would `import WebReader from '@nypl/web-reader'`.

A few places we are importing the WebReader in other NYPL applications so you can see how we are using it in a real app:
- Circulation Patron Web: https://github.com/NYPL-Simplified/circulation-patron-web/blob/7ff22a9c66406d9bd3f783769ea34a09a663f4f2/src/components/WebReader.tsx#L139
- Digital Research Books: https://github.com/NYPL/sfr-bookfinder-front-end/blob/d72b4e9fce844468ce982bcd658e3144f60ae2ce/src/components/ReaderLayout/ReaderLayout.tsx#L92

**Comment by AntonOfTheWoods** [comment]
Thanks very much @samanthaandrews and @hokei for your replies. I fully understand that resource constraints mean you can't maintain a dual stack of internal and external. I am also very interested to see that `initWebReaderSW();` is used in https://github.com/NYPL-Simplified/circulation-patron-web. I was completely unable to get this working properly without actually copy/pasting the code into my own, webpack-driven environment. 

In any case, seeing I have `NYPL-Simplified/circulation-patron-web` to get inspiration from, we can close this.

Maybe this is simply an experience thing - I have only been doing significant amounts of modern web development for around a year, and it seems that becoming comfortable with web stuff takes much more than an order of magnitude longer than other environments (I was ok with Go after around a month, ruby 6 weeks, etc).

As I write this, I believe I have found the source of some of the errors - I use the service worker as an integral part of my architecture, so it gets included in my development mode. I am pretty sure that unless the code in `ui/hooks/useFullScreen.ts` get tree-shaken out of the generated bundle for the service worker, it will fail when trying to run. As you don't have the service worker in development mode and it gets removed for production, you will never see this.

Even after copy/pasting all the code into my project, I was still getting the service worker registration code inteferring with/overidding/breaking my (basic) existing workbox service worker caching. My code was working fine, then when adding the `initWebReaderSW` to the end of my service worker it broke my existing caching (caching web-reader resources worked fine though!). The files were actually cached but the only way I could get it to route/serve both was to copy the code and paste my own cache additions (mainly just `precacheAndRoute(self.__WB_MANIFEST);`) actually into the `initWebReaderSW` code (after the install code). This may also be related to dev vs prod issues though, as I don't think many use SWs the way I do (yet anyway!).
